// <auto-generated />
namespace AppASM2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User10));
        
        string IMigrationMetadata.Id
        {
            get { return "202012150310016_User-1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
